version: "3.8"
services:
  hackorbust_api:
    build: ./hackorbust_api
    container_name: hackorbust_api_c
    ports:
      - '55623:55623'
    volumes:
      - ./hackorbust_api:/app
      - /app/node_modules
  hackorbustapp:
    build: ./hackorbustapp
    container_name: hackorbustapp_c
    ports:
      - '3000:3000'
    volumes:
      - ./hackorbustapp:/app
      - /app/node_modules
    stdin_open: true
    tty: true