version: "3.8"
services:
  hackorbust_api:
    build: ./hackorbust_api
    container_name: hackorbust_api_c
    ports:
      - '4000:4000'
    volumes:
      - ./hackorbust_api:/app
      - /app/node_modules